### PR TITLE
[FW] c1

### PR DESCRIPTION
**Pull request by xmo-odoo**
Forward-Port-Of: odoo-mergebot-testing-org/ignore_proj_2s-Wqw-0#1

### CODE REVIEW

**Comment by xmo-odoo** [comment]
[Pull request status dashboard](http://localhost:8069/odoo-mergebot-testing-org/ignore_proj_2s-Wqw-0/pull/2).

**Comment by xmo-odoo** [comment]
@xmo-odoo @odoomergebotsacrifice-reviewer cherrypicking of pull request odoo-mergebot-testing-org/ignore_proj_2s-Wqw-0#1 failed.

* 4c2efa92377f182264161590ae84927c9a9ebf8f <- on this commit
* 289799ecd07e1fb9c4a5a95745c212ea990377fe

stdout:
```
Auto-merging g
CONFLICT (add/add): Merge conflict in g

```

stderr:
```
14:29:28.169966 git.c:460               trace: built-in: git cherry-pick 4c2efa92377f182264161590ae84927c9a9ebf8f
error: could not apply 4c2efa9... c0
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by odoomergebotsacrifice-reviewer** [comment]
hansen r+

**Comment by xmo-odoo** [comment]
@xmo-odoo @odoomergebotsacrifice-reviewer unable to stage: All commits must have author and committer email, missing email on 48279bbb73fa881bd6530ff3feed184be85408bc indicates the authorship is most likely incorrect.

**Pull request closed without merging**
